### ISSUE TITLE
Update angualr dependencies to major release 4.x.x

### ISSUE THREAD

**Issue by ayoung8** [hres/cfg-classification-webapp#1]
Rebuilt with npm. However, there seem to be issue with dependencies:

> sudo ng build
> Hash: afca470d1d7f79db78dd                                                               
> Time: 16990ms
> chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
> chunk    {1} main.bundle.js, main.bundle.js.map (main) 52.8 kB {3} [initial] [rendered]
> chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 38.5 kB {4} [initial] [rendered]
> chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.6 MB [initial] [rendered]
> chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
> 
> ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CONFIG_OBJ in /opt/angular/cfg-classification-webapp/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol RestangularModule.forRoot in /opt/angular/cfg-classification-webapp/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol AppModule in /opt/angular/cfg-classification-webapp/src/app/app.module.ts, resolving symbol AppModule in /opt/angular/cfg-classification-webapp/src/app/app.module.ts
> 
> ERROR in multi ./src/styles.css ./~/ag-grid/dist/styles/ag-grid.css ./~/ag-grid/dist/styles/theme-fresh.css ./theme-gc/theme-gc-intranet/css/theme.min.css
> Module not found: Error: Can't resolve '/opt/angular/cfg-classification-webapp/theme-gc/theme-gc-intranet/css/theme.min.css' in '/opt/angular/cfg-classification-webapp'
>  @ multi ./src/styles.css ./~/ag-grid/dist/styles/ag-grid.css ./~/ag-grid/dist/styles/theme-fresh.css ./theme-gc/theme-gc-intranet/css/theme.min.css
> 
> ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./src/styles.css
> Module not found: Error: Can't resolve '@angular/material/core/theming/prebuilt/deeppurple-amber.css' in '/opt/angular/cfg-classification-webapp/src'
>  @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./src/styles.css 3:10-201
>  @ ./src/styles.css
>  @ multi ./src/styles.css ./~/ag-grid/dist/styles/ag-grid.css ./~/ag-grid/dist/styles/theme-fresh.css ./theme-gc/theme-gc-intranet/css/theme.min.csss

As the error indicates:
theme-gc folder does not exist. Perhaps it was not committed.
there are missing files and themes.

If there are other dependencies please be sure to list them in the Readme

When doing npm install, the following warnings occurred  they may or not be related to the above errors:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN ng2-restangular@0.1.30 requires a peer of @angular/core@^2.0.0 but none was installed.
> npm WARN ng2-restangular@0.1.30 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
> npm WARN ng2-restangular@0.1.30 requires a peer of @angular/http@^2.0.0 but none was installed.
> npm WARN @angular/platform-browser@2.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
> npm WARN @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none was installed.

**Comment by luc-bertrand** [comment]
I verified project this morning.  Added some updated third party libraries and missing GC WET4 theme files.  Verified successful build with above additions.  Please try again.

**Comment by ayoung8** [comment]
Pulled commits and deployed. The latest changes are at: https://lam-dev.hres.ca/cfg-classification-webapp
If any problems open a new issue here.
