### ISSUE TITLE
Need a new hres repo

### ISSUE THREAD

**Issue by luc-bertrand** [hres/cfg-classification-webapp#14]
Need a new repository to store keycloak source code.  Perhaps hres/cfg-classification-keycloak

Thanks,

Luc

**Comment by ayoung8** [comment]
This project currently has several repos ... 
https://github.com/hres/cfg-task-service
https://github.com/hres/cfg-classification-webapp
https://github.com/hres/cfg-classification-service
https://github.com/hres/fcdr
https://github.com/hres/346R1
https://github.com/hres/346R2

Is another one required?

**Comment by luc-bertrand** [comment]
I am not familiar with the last 3 above mentioned repos but to answer your question, Yes.

**Comment by ayoung8** [comment]
already advised Jane repo created.
You even committed to it already
Suggest some time be taken to clean up the stale issues.
