### ISSUE TITLE
Automate Angular build and deployment process

### ISSUE THREAD

**Issue by luc-bertrand** [hres/cfg-classification-webapp#2]
This issue was created to better track [https://github.com/hc-sc/FCDR/issues/147](https://github.com/hc-sc/FCDR/issues/147) under the hres umbrella

**Comment by ayoung8** [comment]
will setup nightly deployments and double back to full automation later

**Comment by ayoung8** [comment]
Daily updates will happen at 0617 every morning.

**Comment by luc-bertrand** [comment]
Daily builds are not correct.  They appear stagnant in that they don't seem to be happening as there are no visible changes from day to day.  Please verify.

**Comment by ayoung8** [comment]
Daily builds are correct. 

```
# [ -x /opt/angular/deploy-angular.sh ] && /opt/angular/deploy-angular.sh cfg-classification-webapp
Already up-to-date.
Hash: e98ce32228ea206f20f5                                                               
Time: 19678ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 71.1 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 276 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.71 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

syslog.1:395:Apr 21 06:17:01 lam-dev CRON[8104]: (root) CMD ([ -x /opt/angular/deploy-angular.sh ] && /opt/angular/deploy-angular.sh cfg-classification-webapp > /dev/null)
```

The last commit before the 0617 deploy was commit 772973f4ddf19b428e5d886c6395bc74c62722db from Thu Apr 20 11:36:00 2017 -0400, and that is what was available online before the manual trigger 

Looking at the github repo, https://github.com/hres/cfg-classification-webapp shows "Latest commit 7177daf"

We manual triggered the process and that commit was brought online. 

```
git branch -v
* master 7177daf wired all editable grid fields to corresponding cell editors
```

That said, please ensure whatever you want to see online is commit and pushed to the repo before 0617 every morning any other commits will only go online the next day until full CI is available.

If this is insufficient, I can add one additional deploy time mid day just specify what time you would like that to be.

**Comment by luc-bertrand** [comment]
Keeping this open, as the requirement is for Continuous Integration with access to the build artifacts.

**Comment by ayoung8** [comment]
Seems to be a duplicate issue,
If deployment directives have changes please update the readme.md with the relevant info and create a new issue.

**Comment by luc-bertrand** [comment]
The application builds are not the same as the local builds.  The build is non functional, cannot verify continuous integration since app is not working

**Comment by luc-bertrand** [comment]
Hi Anthony,

Could you execute the following command in the root of the cfg-classification-webapp folder and get back to me with the response?

_npm list  &#064;angular &#047;material_

**Comment by ayoung8** [comment]
No action on this issue.

> Automate Angular build and deployment process
Issue will remain open as requested but muted.
New issues will be reopened

**Comment by luc-bertrand** [comment]
From the output listed in [Issue#11](https://github.com/hres/cfg-classification-webapp/issues/11) it seems like libraries are badly out of date.  Please execute the following two commands from the root of the cfg-classification-webapp folder.

_rm -rf node_modules
npm install_

**Comment by luc-bertrand** [comment]
![image](https://user-images.githubusercontent.com/24926762/28216847-049912e6-6881-11e7-8362-05c07834dee7.png)
The above screen shot displays the error that is preventing us from closing this ticket which specifies that the build must be automated but it also needs to be functional.

**Comment by ayoung8** [comment]
Done Tracked in #11

**Comment by luc-bertrand** [comment]
Verified on lam-dev.hres.ca  Works.
