### ISSUE TITLE
Setup reverse proxy on apache

### ISSUE THREAD

**Issue by luc-bertrand** [hres/cfg-classification-webapp#7]
The following path needs to be reverse proxied on lam-dev

/cfg-task-service/    to    http://java-dev.hres.ca/cfg-task-service/

If there is a port on java-dev than specify the port above.

**Comment by ayoung8** [comment]
This approach doesn't make that much sense. 

The better approach would be to have a config file in cfg-classification-webapp which points to something configurable (in this case https://java-dev.hres.ca/) this way the code base is independent of server environment and allows the app to move between environments independent of the server and/or DNS. 

In fact the same config file can be used to point to the IP address of the local dev host for the task-service and classification-service as well 

And once everything is fully developed and accepted the config file can be updated to use a *.canada.ca DNS entry point.

The readme.md should be updated to indicate how to use the config file

**Comment by luc-bertrand** [comment]
One of the reasons we are using Apache is because with two lines of config settings we can reverse proxy to wherever the app gets deployed and the code does not need to be recompiled.  It also fixes our cross domain policy problem.

**Comment by ayoung8** [comment]
Locking code to server config is a bad practice that causes potential downstream compatible and portability issues 

Also as a shared server  there's no guarantee  that the production will be Apache

**Comment by luc-bertrand** [comment]
The instructions to configure the reverse proxy have been added to the README.md of cfg-classification-webapp.

The project architect defined the Apache 2 web server requirement months ago in the Solution Architecture document.
